version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_config:/etc/prometheus
volumes:
  prometheus_config:
    driver: local
