version: '3'

services:
  ubuntu:
    privileged: true
    image: congttl/ubuntu
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 80:80
      - "22:22"
      - 443:443
      - 3000:3000
      - 9090:9090
      - 8080:8080
      - 8001:8001
