version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      DATABASE_USER: congnt
      DATABASE_PASSWORD: password
      DATABASE_HOSTNAME: "127.0.0.1"
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
  redis-data:
    driver: local
