version: '3'

services:
  certbot:
    image: certbot/certbot
    container_name: letsencrypt
    volumes:
      - ./certbot_root:/var/www/certbot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email nguyenthanhcong101096@gmail.com --agree-tos --no-eff-email -d autodeploy.today  -d www.autodeploy.today

  nginx:
    image: nginx
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot_root:/var/www/certbot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt

volumes:
  certbot-etc:
    driver: local
  certbot-var:
    driver: local
  certbot_root:
    driver: local
